import React, { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import logo from "../assets/logo.png";

const ConsumerTOS: React.FC = () => {
  const navigate = useNavigate();

  // ✅ Scroll to top when page loads
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  return (
    <div className="min-h-screen bg-white text-[#1e1e1e] flex flex-col">
      {/* Header */}
      <header className="w-full bg-white sticky top-0 z-10 border-b border-gray-100 shadow-sm">
        <div className="max-w-7xl mx-auto flex justify-between items-center px-6 py-8">
          <div>
            <h1 className="text-4xl md:text-6xl font-extrabold bg-gradient-to-r from-[#EC1E79] via-[#F45BA0] to-[#3345B0] bg-clip-text text-transparent drop-shadow-sm">
              Consumer Terms of Service
            </h1>
            <p className="text-gray-600 text-base md:text-lg mt-3 drop-shadow-[1px_1px_2px_rgba(0,0,0,0.3)]">
              These terms govern your use of OfferBeez services as a consumer.
              Please read them carefully.
            </p>
          </div>

          {/* ✅ Updated Button: navigate + scroll to footer */}
      <button
            onClick={() => navigate("/", { state: { scrollToFooter: true } })}
            className="bg-gradient-to-r from-[#EC1E79] via-[#F45BA0] to-[#3345B0] text-white font-semibold px-6 py-3 rounded-lg shadow-md hover:shadow-lg hover:scale-[1.03] transition-all duration-300"
          >
            Home
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto w-full flex flex-col gap-10 px-6 py-16 text-gray-800 leading-relaxed text-[15px]">
        {/* Version and Logo */}
        {/* <div className="flex justify-between items-start flex-wrap mb-8">
          <p className="text-sm text-gray-500 mt-2">Version 1.0</p>
          <img
            src={logo}
            alt="OfferBeez Logo"
            className="w-[120px] md:w-[180px] object-contain mt-6 opacity-90"
          />
        </div> */}

        {/* Version and Logo */}
        <div className="relative mb-8">
          {/* Watermark Image */}
          <img
            src={logo}
            alt="OfferBeez Logo Watermark"
            className="absolute inset-0 mx-auto opacity-10 w-[250px] md:w-[400px] object-contain select-none pointer-events-none"
            style={{
              top: "950%",
              left: "50%",
              transform: "translate(-50%, -50%)",
              zIndex: 0,
            }}
          />

          {/* Foreground Content */}
          <div className="relative flex justify-between items-start flex-wrap z-10">
            <p className="text-sm text-gray-500 mt-2">Version 1.0</p>
          </div>
        </div>

        {/* Last Updated */}
        <p className="text-sm text-gray-700 mb-10">
          <span className="font-semibold">Last updated:</span>{" "}
          <span className="text-[#EC1E79] font-semibold">
            24th October 2025
          </span>
        </p>

        {/* TOS Content */}
        <div className="space-y-10 text-justify leading-relaxed text-[#1e1e1e]">
          {/* Intro */}
          <p>
            This document is an electronic record and published in accordance
            with the provisions of the Information Technology Act, 2000, and the
            rules thereunder, including the Information Technology (Intermediary
            Guidelines and Digital Media Ethics Code) Rules, 2021. It is
            generated by a computer system and does not require any physical or
            digital signatures.
          </p>

          {/* Section 1 */}
          <div className="text-[#1a1a1a]">
            {/* ---------- 1. Terms of Use ---------- */}
            <h2 className="font-bold mb-4">1. Terms of Use:</h2>

            <p className="mb-4">
              The websites{" "}
              <a
                href="https://www.offerbeez.in"
                className="text-[#3345B0] hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                www.OfferBeez.in
              </a>{" "}
              and{" "}
              <a
                href="https://www.venturebiz.in"
                className="text-[#3345B0] hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                www.Venturebiz.in
              </a>{" "}
              (the “Website”) and the mobile application ‘OfferBeez’ (the “App”)
              (collectively referred to as the “Platform”) are owned, operated,
              and managed by OfferBeez Marketplace Private Limited — a private
              limited company incorporated under the provisions of the Indian
              Companies Act, 2013, having its registered office at #2085/16, 2nd
              Floor, Spoorthi, Puttenahalli Main Road, JP Nagar 7th Phase,
              Bangalore – 560078.
            </p>

            <p className="mb-4">
              These terms of use (“Terms”) govern your use of the Platform, and
              for the purpose of these Terms, Venturbiz Promotions Private
              Limited, including its subsidiaries, its holding company, and its
              affiliates, may, wherever the context so requires, be also
              referred to as “OfferBeez”, “Company”, “We”, “Us”, or “Our”, and
              the terms “You”, “Your”, or “User” refer to the user of the
              Platform. We value the trust you have placed in us, and hence, we
              maintain reasonable security standards for securing the
              transactions and your information.
            </p>

            <p className="mb-4">
              Please read these terms carefully before you use the platform. If
              you do not agree to these terms, you may not use the offers on the
              platform, and we request you uninstall the app and not access the
              platform. By even merely using/accessing the Platform, You shall
              be contracting with OfferBeez, and You signify Your acceptance of
              these Terms and other OfferBeez policies (including but not
              limited to the cancellation & refund terms and published privacy
              policy (‘Privacy Notice’’) as posted on the Platform and amended
              from time to time), which takes effect on the date on which You
              use the Platform and thereby create a legally binding agreement to
              abide by the same. Further, by furnishing Your personal
              information, You consent to OfferBeez accessing Your personal
              information for the purpose of enabling transactions. You also
              agree that you are interested in availing the offers through the
              platform in accordance with these terms.
            </p>

            <p className="mb-4">
              a) OfferBeez retains an unconditional right to modify or amend
              these Terms. You can determine when these Terms were last modified
              by referring to the ‘Last Updated’ legend above. You can access
              the latest version of these Terms at any given time on the
              Platform. You should regularly review the terms on the platform.
              OfferBeez reserves the right to amend, suspend, discontinue or add
              any or all Offers without prior notice and can add or remove
              relevant terms and conditions, if necessary.
            </p>

            <p className="mb-4">
              b) Any updating of the terms as a consequence of changes in legal
              and regulatory compliances shall be made in compliance thereof.
              Your continued use of and access to the Platform shall be your
              consent to any changes made by us in these terms. In the event the
              modified terms are not acceptable to you, you should discontinue
              accessing the platform.
            </p>

            {/* ---------- 2. Access to Offers ---------- */}
            <h2 className="font-bold mt-6 mb-4">2. Access to Offers:</h2>

            <p className="mb-4">
              a) OfferBeez is a digital advertising platform that allows the
              businesses to publish their offers/advertisements. Consumers can
              view the products (defined hereunder) and offers offered for sale
              by these sellers either in general or specific to the locations of
              the consumers.
            </p>

            <p className="mb-4">
              b) OfferBeez is only responsible for creating the advertising
              platform for businesses and users to see the ads. The company is
              not responsible for the offer advertised by businesses. The
              transactions are done offline and between the business and user.
            </p>

            <p className="mb-4">
              c) OfferBeez is not a party to or in control of in any manner any
              transaction between the platform's users and sellers.
            </p>

            <p className="mb-4">
              d) You acknowledge that the Platform allows You to avail a
              personal, limited, non-exclusive, non-transferable, and revocable
              privilege to access and use the Platform for the purposes of
              seeing the advertisement on consumer goods or services businesses
              and individuals for grocery, apparel, electronics, health and
              wellness products, including prepared foods and beverages (Café
              orders), pet care, etc. (collectively,
            </p>

            <p className="mb-4">
              e) “Product(s)”) from the Sellers on a business to consumer (B2C).
              The registered businesses may be required to furnish additional
              details of their business, including, without limitation, business
              name, GSTIN, licences/registrations issued by government
              authorities and/or any other information that may be required by
              OfferBeez. The user shall not be responsible for the accuracy of
              the GSTIN and legal entity name. OfferBeez disclaims any
              liabilities arising out of incorrect details.
            </p>

            <p className="mb-4">
              f) Businesses publishing their offers are solely responsible for
              all the details of the offer, including the business name,
              location, actual offer, pricing, discounts, quality, availability,
              etc.
            </p>

            <p className="mb-4">
              g) The aforesaid revocable privilege to access does not
              include/permit resale or commercial use of the Platform or its
              Content (as defined below) in any manner. The Sellers may, at
              their discretion, add, modify or remove any of the Offers listed
              above from time to time without notice.
            </p>

            <p className="mb-4">
              h) The Sellers and/or OfferBeez may also make applicable, at its
              discretion, additional terms and conditions specific to any
              category or section of Products or Offers in addition to these
              Terms, and Your purchase of any of such category or section of
              Products or Offers shall also be governed by such additional terms
              and conditions. OfferBeez reserves the right to provide the Offers
              in any area or city in India, as may be determined by OfferBeez in
              its sole discretion. Before applying or registering for availing
              any of the Offers, We request You to please check if the Offers
              are available in Your area or city.
            </p>

            <p className="mb-4">
              i) Offers are ranked organically unless promoted through
              advertisements. Ranking is based on popularity indicators like
              impressions, user preferences, relevance, add-to-cart actions,
              etc. Newly launched products receive a temporary visibility boost
              to enhance exposure and assess popularity. OfferBeez does not: (i)
              adopt any ‘unfair trade practices’ on the Platform or otherwise
              with respect to its Offers; (ii) discriminate between Users of the
              same class or make any arbitrary classification of the Users; and
              (iii) discriminate between the third-party delivery service
              providers.
            </p>

            <p className="mb-4">
              j) OfferBeez functions as an online promotions platform and acts
              as a facilitator between users and sellers on the platform. At no
              point does OfferBeez take possession of products offered by
              sellers, nor does it hold any rights, title or interest in those
              products and offers. OfferBeez is not liable for any obligations
              related to non-performance or breach of contracts between users
              and sellers, as that is a bilateral arrangement between you and
              the seller. Furthermore, OfferBeez is neither responsible for poor
              or delayed product or service performance nor for issues arising
              from products that are out of stock or unavailable.
            </p>

            {/* ---------- 3. Terms & Conditions for Registered Business ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              3. Terms and Conditions Applicable for a User Who Is a Registered
              Business:
            </h2>

            <p className="mb-4">· The User represents and undertakes</p>

            <p className="mb-4">
              · That the documents and information provided are genuine and
              complete
            </p>

            <p className="mb-4">
              · That the User shall not act as an agent of OfferBeez.
            </p>

            <p className="mb-4">
              · To adhere to such other terms as may be applicable or displayed
              on the platform from time to time.
            </p>

            {/* ---------- 4. Age and Eligibility ---------- */}
            <h2 className="font-bold mt-6 mb-4">4. Age and Eligibility:</h2>

            <p className="mb-4">
              The Products and Offers are minors, i.e., persons under the age of
              18 (eighteen) years, undischarged insolvents, or any Users who are
              not competent to enter into a contract under the Indian Contract
              Act, 1872, unless otherwise provided hereunder or to anyone
              previously suspended or removed by OfferBeez from availing the
              Products or Offers or accessing the Platform. You hereby represent
              that you are:
            </p>

            <p className="mb-4">a) Of legal age to form a binding contract,</p>

            <p className="mb-4">
              b) Not a person barred from receiving the offers from the platform
              under the applicable laws;
            </p>

            <p className="mb-4">
              c) Competent to enter into a binding contract
            </p>

            <p className="mb-4">
              d) Have not been previously suspended or removed or disqualified
              for any reason from the platform. If you are under the age of 18,
              you shall use and access the platform only with the express
              consent of a parent or guardian and under their supervision.
            </p>

            <p className="mb-4">
              e) You shall not make negative, defamatory, misleading, deceptive,
              or libellous remarks about us or our brand, including OfferBeez
              and its agnates and cognates, on the platform or otherwise, or
              take any actions that could harm OfferBeez's reputation or dilute
              its trademarks. Additionally, You will not impose an excessive
              load on the Platform's infrastructure or Our systems and networks.
            </p>

            {/* ---------- 5. User Account and Security ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              5. User Account and Security:
            </h2>

            <p className="mb-4">
              a) In order to access the offers of the platform, you will have to
              register and create an account on the platform by providing
              details as may be required (“Account”). When you use the platform,
              OfferBeez may collect personal information such as your name,
              email, age, photograph, address, mobile number, and contact
              details, and also documents pertaining to the same. This includes
              demographic information like gender, occupation, and education, as
              well as your activity on the platform, such as visited pages,
              clicked links, and transaction details, including financial
              information needed to provide offers and manage the platform
              effectively.
            </p>

            <p className="mb-4">
              b) You are solely responsible for the information you provide to
              us. You shall ensure and confirm that the account information and
              all information provided by you is complete, accurate and
              up-to-date. If there is any change in the account information, or
              if any information is found to be incomplete or incorrect, you
              shall promptly update your account information on the platform or
              request OfferBeez for information revision or update. If the
              information provided by you is untrue, inaccurate, unauthorised,
              not current, or incomplete (or becomes untrue, inaccurate, not
              current, or incomplete), OfferBeez reserves the right to refuse
              any and all the offers if OfferBeez has reasonable grounds to
              suspect that such information is untrue, inaccurate, not current,
              or incomplete or for any reasons of government policy of state and
              central or anything offensive or hurtful on religious grounds or
              anything that OfferBeez thinks is not in the right sense of
              promotion of the business. OfferBeez reserves the right to refuse
              access to the Platform at any time without notice.
            </p>

            <p className="mb-4">
              c) Confidentiality of the account credentials shall be your
              responsibility. OfferBeez disclaims any liability for losses due
              to unauthorised access of your account.
            </p>

            {/* ---------- 6. Price of Products and Offers ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              6. Price of Products and Offers:
            </h2>

            <p className="mb-4">
              a) The prices for products and offers listed by sellers on the
              platform are determined entirely by the sellers themselves, and
              OfferBeez does not participate in or influence this pricing
              process in any manner. The prices of each of the products and
              offers may vary due to various factors, and you may check the
              price with the business before purchasing the product.
            </p>

            <p className="mb-4">
              b) All the products listed on the platform will be sold at Indian
              Rupees, either at Maximum Retail Price (MRP) (inclusive of all
              taxes) or at a discounted price unless otherwise specified
              directly by the business. The prices of the Products and Offers
              are an offer for sale by the Sellers and may be modified by the
              Sellers from time to time without any prior notice. OfferBeez
              endeavour to display the products and offers at the most accurate
              prices possible on the platform. There may be inadvertent errors
              with respect to the price and other information of the products or
              offers. You may bring to Our notice of such errors and We shall
              effect necessary corrections.
            </p>

            <p className="mb-4">
              c) The Users will be informed about all the costs that may be
              levied on the purchase of the Products or Offers on the platform.
            </p>

            <p className="mb-4">
              d) The expression 'Lowest Prices' pertains to the computation of
              average prices for all Products and Offers offered for sale by the
              Sellers on the Platform (in comparison to competitors in the quick
              commerce segment for groceries, in most of the cases) and are
              subject to availability of stocks. OfferBeez expressly disclaims
              any liability associated with the individual products or offers
              sold on the platform by the sellers.
            </p>

            <p className="mb-4">
              e) Alcoholic beverages, tobacco products and other banned products
              are strictly not to be sold by the businesses either directly or
              indirectly or through reference or in any concealed manner to
              provide any leads to banned products or anything that is not
              approved by the government.
            </p>

            <p className="mb-4">
              f) Businesses and consumers are directly responsible in the event
              of such activities, and OfferBeez is not responsible for the
              legalities. OfferBeez will make all coordination and efforts with
              legal authorities to ensure the platform is not used for any
              banned activities.
            </p>

            <p className="mb-4">
              g) Terms and Conditions for Purchase of Pharmaceutical Products
              and Telemedicine Consultations - OfferBeez’s Role and Disclaimer
              of Liability - OfferBeez operates solely as a digital advertising
              marketplace platform and does not sell pharmaceutical products.
              The medical stores may post their offers and discounts as per
              applicable laws and permissions or for their locations to help get
              discovered.
            </p>

            <p className="mb-4">
              h) Any medical-related services are solely the responsibility of
              the individual service providers, like telemedicine consultation,
              etc. OfferBeez does not offer medical advice or consultations on
              health matters. All materials accessible through the Platform,
              including articles, blogs, images, and other informational
              content, serve purely academic purposes and do not substitute for
              direct professional healthcare advice. Telemedicine consultations
              available on the platform are offered through independent
              contractors ("Telemedicine Consultants") engaged by the user
              solely at their discretion. The opinions and guidance provided by
              telemedicine users are encouraged to consult in-person healthcare
              providers as needed to confirm any information or recommendations
              received from telemedicine consultants.
            </p>

            {/* ---------- 7. User Care ---------- */}
            <h2 className="font-bold mt-6 mb-4">7. User Care:</h2>

            <p className="mb-4">
              The user acknowledges and agrees that OfferBeez shall not be held
              liable for the quality of the seller’s offers or products, or any
              issues arising from offers provided by third-party delivery
              service providers that do not meet user expectations, potentially
              resulting in loss, harm, or damage.
            </p>

            <p className="mb-4">
              a) The non-availability of products or offers, incorrect orders
              fulfilled by the seller, or any liability associated with products
              sold by the seller.
            </p>

            <p className="mb-4">
              b) The information about products and the associated catalogue,
              including pricing, displayed on the platform is provided by the
              sellers. OfferBeez cannot be held liable for any changes,
              correctness or errors or omissions of the information, or
              unavailability of these products and offers.
            </p>

            <p className="mb-4">
              c) OfferBeez is not and cannot be a party to any transaction
              between consumers and sellers or have any control, involvement or
              influence over the products purchased/offers availed by you from
              such sellers. You acknowledge and agree that OfferBeez shall not,
              at any time, have any ownership, control, and/or title to any
              Product(s), which is subject to a bipartite sale and purchase
              transaction between you and the relevant seller.
            </p>

            <p className="mb-4">
              d) OfferBeez does not provide any warranty or guarantee with
              respect to the products and/or offers offered for sale on the
              platform and disclaims any liability with respect to the
              manufacturing defects, quality, taste, or performance of the
              products/offers sold.
            </p>

            <p className="mb-4">
              e) All commercial and contractual arrangements regarding the
              products and offers offered for sale are solely between users and
              sellers. These arrangements encompass various terms, including but
              not limited to pricing, product and service quality, applicable
              taxes, delivery and other fees, payment conditions, warranties (if
              any), and after-sales support.
            </p>

            <p className="mb-4">
              f) OfferBeez may, however, provide support offers to sellers in
              respect to order fulfilment, mode of payment, payment collection,
              customer support, technology and other ancillary offers, pursuant
              to independent contracts executed between OfferBeez and the
              sellers.
            </p>

            <p className="mb-4">
              g) OfferBeez does not guarantee or endorse the specifics of any,
              including aspects like legal ownership, creditworthiness, or
              identity. We recommend that You conduct Your own due diligence to
              verify the legitimacy of any seller You choose to engage with on
              the platform and exercise Your discretion. All offers from Sellers
              and third parties are governed by their respective terms and
              conditions, and OfferBeez assumes no responsibility for these
              offers. OfferBeez makes the best attempt to review the data
              provided by the business but cannot validate the information
              provided. The user is at their own discretion to verify and
              validate the business before buying or making any purchases.
            </p>

            <p className="mb-4">
              h) You agree and understand that the product images are
              representations of the product and not actual images of the
              product sold to you, and you shall read the physical product label
              for the calorific and nutritional value, using instructions,
              batch, manufacture date, use-by date/shelf life, content, weight,
              manufacturer and the customer support details, as may be relevant,
              before consumption of the products, including but not limited to
              café orders.
            </p>

            <p className="mb-4 font-semibold">
              WHILE EVERY REASONABLE EFFORT IS MADE TO MAINTAIN ACCURACY OF
              INFORMATION ON THE PLATFORM, THE ACTUAL PRODUCT MAY CONTAIN MORE
              AND/OR DIFFERENT INFORMATION THAN WHAT IS SHOWN ON THE PLATFORM.
              IT IS RECOMMENDED TO CHECK WITH THE BUSINESS AND ACTUAL PRODUCT
              AND DIRECTLY REFER TO THE INFORMATION PRESENTED ON THE ACTUAL
              PRODUCT BY THE BUSINESS.
            </p>

            <p className="mb-4">
              i) As a result of such checks, if OfferBeez is not satisfied with
              the credibility of the user or genuineness, it will have the right
              to reject the order(s) placed by such users or disable their
              access to the platform. Transactions on the Platform may be
              delayed, suspended, or cancelled at OfferBeez's sole discretion
              for any reason (to maintain the integrity, security, and equitable
              usage of the Platform), including but not limited to suspicious
              activities, concerns regarding the user's authenticity or
              behaviour, unusually high transaction volumes, safety concerns, or
              to ensure the fair use of the Platform.
            </p>

            {/* ---------- 8. Beware of Fraud ---------- */}
            <h2 className="font-bold mt-6 mb-4">8. Beware of Fraud:</h2>

            <p className="mb-4">
              Please do not share your debit/credit card number, CVV number,
              OTP, UPI/ATM pin and other sensitive information with anyone
              claiming to be an OfferBeez representative. OfferBeez or its
              authorised representatives will NEVER ask you to share the
              aforesaid details. Beware of fraudsters, and please report
              incidents immediately to your bank, the nearest police station and
              at{" "}
              <a
                href="https://cybercrime.gov.in/"
                className="text-[#3345B0] hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                https://cybercrime.gov.in/
              </a>
              .
            </p>

            <p className="mb-4">
              a) For assistance on an OfferBeez order or refund-related issues,
              click on the ‘Get Help’ or ‘Contact Us’ section on the app or
              contact{" "}
              <a
                href="mailto:support@offerbeez.in"
                className="text-[#3345B0] hover:underline"
              >
                support@offerbeez.in
              </a>
              .
            </p>

            <p className="mb-4">
              b) Please exercise caution to verify the portals/website links
              claiming to be OfferBeez or a lookalike or a payment link shared
              over social media or a social messaging app claiming to be
              OfferBeez discounts or offers and proactive calls from
              unauthorised numbers or unauthorised social media accounts
              requesting personal/financial information.
            </p>

            {/* ---------- 9. Use of Platform ---------- */}
            <h2 className="font-bold mt-6 mb-4">9. Use of Platform:</h2>

            <p className="mb-4">
              Subject to compliance with the Terms, OfferBeez hereby grants you
              a personal, non-exclusive, non-transferable, limited, revocable
              privilege to access and use the Platform. You agree to use the
              Platform only:
            </p>

            <p className="mb-4">
              · For purposes that are permitted by the Terms
            </p>

            <p className="mb-4">
              · In accordance with any applicable law, regulation or generally
              accepted practices or guidelines
            </p>

            <p className="mb-4">
              · For availing the offers through the platform. You agree not to
              engage in activities that may adversely affect the use of the
              Platform by OfferBeez and/or other users.
            </p>

            <p className="mb-4">
              a) You agree that the Platform or any portion of the Platform
              shall not be reproduced, duplicated, copied, sold, resold or
              otherwise exploited for commercial purposes.
            </p>

            <p className="mb-4">
              b) You agree to not frame or utilise the framing techniques to
              enclose any trademark, logo or any other proprietorship
              information of the platform.
            </p>

            <p className="mb-4">
              c) You agree not to access (or attempt to access) the Platform by
              any means other than through the interface that is provided by
              OfferBeez. You shall not use any deep link, robot, spider or other
              automatic device, program, algorithm or methodology, or any
              similar or equivalent manual process, to access, acquire, copy or
              monitor any portion of the Platform or Content, or in any way
              reproduce or circumvent the navigational structure or presentation
              of the Platform, materials or any Content, to obtain or attempt to
              obtain any materials, documents or information through any means
              not specifically made available through the Platform.
            </p>

            <p className="mb-4">
              d) You undertake not to host, display, upload, modify, publish,
              transmit, store, update or share any information that:
            </p>

            <p className="mb-4">
              1) Belongs to another person and to which the User does not have
              any right
            </p>

            <p className="mb-4">
              2) Is defamatory, obscene, pornographic, paedophilic, invasive of
              another's privacy, including bodily privacy, insulting, or
              harassing on the basis of gender; libellous; racially or
              ethnically objectionable; relating or encouraging money laundering
              or gambling; or otherwise inconsistent with or contrary to the
              laws in force
            </p>

            <p className="mb-4">3) Is harmful to child;</p>

            <p className="mb-4">
              4) Infringes any patent, trademark, copyright, or other
              proprietary rights;
            </p>

            <p className="mb-4">
              5) Violates any law for the time being in force;
            </p>

            <p className="mb-4">6) Impersonates another person;</p>

            <p className="mb-4">
              7) Threatens the unity, integrity, defence, security or
              sovereignty of India, friendly relations with foreign States, or
              public order, or causes incitement to the commission of any
              cognisable offence, or prevents investigation of any offence or is
              insulting other nation;
            </p>

            <p className="mb-4">
              8) Contains software virus or any other computer code, file or
              program designed to interrupt, destroy, or limit the functionality
              of any computer resource;
            </p>

            <p className="mb-4">
              9) Is patently false and untrue, and is written or published in
              any form, with the intent to mislead or harass a person, entity,
              or agency for financial gain or to cause any injury to any person;
            </p>

            <p className="mb-4">
              e) Disrupt or interfere with the security of, or otherwise cause
              harm to, the Platform, systems resources, accounts, passwords,
              servers, or networks connected to or accessible through the
              Platform or any affiliated or linked sites;
            </p>

            <p className="mb-4">
              f) Violate the Terms contained herein or elsewhere; and
            </p>

            <p className="mb-4">
              g) Reverse engineer, modify, copy, distribute, transmit, display,
              perform, reproduce, publish, license, create derivative works
              from, transfer, or sell any information or software obtained from
              the Platform.
            </p>

            <p className="mb-4">
              h) You shall solely be responsible for maintaining the necessary
              computer equipment, gadgets and internet connections that may be
              required to access, use and transact on the platform.
            </p>

            <p className="mb-4">
              i) You understand and acknowledge that by using the Platform or
              any of the Offers, you may encounter Content that may be deemed by
              some Users to be offensive, indecent, or objectionable, which
              Content may or may not be identified as such. You agree to use the
              Platform and any Offers at your sole risk and that to the fullest
              extent permitted under applicable law. Offerbeez shall have no
              liability to you for content that may be deemed offensive,
              indecent, or objectionable to you.
            </p>

            {/* ---------- 10. Intellectual Property Rights related ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              10. Intellectual Property Rights related:
            </h2>

            <p className="mb-4">
              a) - The Non-Offer-related content – the platform and the
              processes, and their selection and arrangement, including but not
              limited to texts, videos, graphics, user interfaces, visual
              interfaces, sounds and music (if any), artwork and computer code
              (and any combinations thereof) (collectively, the “Content”) on
              the platform – is either owned by or licensed by OfferBeez, and
              the design, structure, selection, coordination, expression, look
              and feel and arrangement of such Content are protected by
              copyright, patent and trademark laws and various other
              intellectual property rights.
            </p>

            <p className="mb-4">
              b) The trademarks, logos and service marks displayed on the
              Platform (“Marks”) are the licensed property of OfferBeez. You are
              not permitted to use the Marks without the prior consent of
              OfferBeez. Access to or use of the Platform does not authorise any
              party to use trademarks, logos, or any other mark in any manner.
            </p>

            <p className="mb-4">
              c) OfferBeez disclaims holding any right, title, or interest in
              and to the intellectual property rights arising out of or
              associated with the products and offers sold by the Sellers on the
              Platform.
            </p>

            <p className="mb-4">
              d) References on the platform of any name, mark, offer or product
              of third parties have been provided for your convenience and in no
              way constitute an endorsement, sponsorship or recommendation,
              whether express or implied.
            </p>

            <p className="mb-4">
              e) Where the platform contains links to other sites provided by
              third parties, these links are provided for information only. We
              have no visibility or control over the contents on or available
              through those sites, and You acknowledge and agree that We have no
              liability for any such content.
            </p>

            <p className="mb-4">
              f) OfferBeez word/Term mark and variances, together with device
              marks displayed on the Platform are licensed property of the
              Company, and any use, unless expressly permitted, shall amount to
              infringement and You shall hereby agree and undertake that You
              recognise Our intellectual property rights and, upon acquiring
              knowledge of any infringement by any third parties, shall report
              to Us at{" "}
              <a
                href="mailto:legal@OfferBeez.in"
                className="text-[#3345B0] hover:underline"
              >
                legal@OfferBeez.in
              </a>
            </p>

            {/* ---------- 11. Disclaimer of Warranties & Liability ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              11. Disclaimer of Warranties & Liability:
            </h2>

            <p className="mb-4">
              a) You expressly understand and agree that, to the maximum extent
              permitted by applicable law.
            </p>

            <p className="mb-4">
              b) The Platform and other Content are provided by OfferBeez on an
              “as is” basis without warranty of any kind, express, implied,
              statutory, or otherwise, including the implied warranties of
              title, non-infringement, merchantability, or fitness for a
              particular purpose. Without limiting the foregoing, OfferBeez
              makes no warranty that the Platform or Offers will meet Your
              requirements, or Your use of the Platform will be uninterrupted,
              timely, secure, or error-free. No advice or information, whether
              oral or written, obtained by you from OfferBeez shall create any
              warranty not expressly stated in the terms.
            </p>

            <p className="mb-4">
              c) OfferBeez will not be liable for any loss that you may incur as
              a consequence of unauthorised use of your account or account
              information in connection with the platform, either with or
              without your knowledge.
            </p>

            <p className="mb-4">
              d) OfferBeez shall not, nor is it obligated to, mediate or resolve
              any disputes or disagreements that may arise between you and the
              sellers.
            </p>

            <p className="mb-4">
              e) OfferBeez does not endorse, either implicitly or explicitly,
              any sale or purchase of products or offers listed on the Platform.
              However, upon receiving a written request from you following the
              purchase of any products and/or offers on the platform, OfferBeez
              may provide additional information about the sellers involved in
              the transaction as available to facilitate direct communication
              between you and sellers for the purpose of dispute resolution.
            </p>

            <p className="mb-4">
              f) OfferBeez has endeavoured to ensure that all the information on
              the Platform is accurate, but OfferBeez neither endeavours nor
              makes any representations regarding the quality, accuracy or
              completeness of any data, information regarding the Offers or
              otherwise. OfferBeez shall not be responsible for the delay or
              inability to use the Platform or related functionalities, the
              provision of or failure to provide functionalities, or for any
              information, software, functionalities, and related graphics
              obtained through the Platform, or otherwise arising out of the use
              of the Platform, whether based on contract, tort, negligence,
              strict liability or otherwise.
            </p>

            <p className="mb-4">
              g) Further, OfferBeez shall not be held responsible for
              non-availability of the Platform during periodic maintenance
              operations or any unplanned suspension of access to the Platform
              that may occur due to technical reasons or for any reasons beyond
              OfferBeez’s reasonable control.
            </p>

            <p className="mb-4">
              h) OfferBeez makes no representation that the Content on the
              Platform is appropriate to be used or accessed outside the
              Republic of India. Any users who use or access the platform from
              outside the Republic of India do so at their own risk and are
              responsible for compliance with the laws of such jurisdiction and
              also consent to OfferBeez for use of their personal and other
              information only for the purpose of provision of offers. By
              visiting the Platform or providing Your information, You expressly
              agree to be bound by these Terms and Our Privacy Notice and also
              agree to be governed by the laws of India, including but not
              limited to the laws applicable to data protection and privacy. If
              you do not agree, please do not use or access our platform.
            </p>

            <p className="mb-4">
              i) The Terms do not constitute, nor may the Terms be used for or
              in connection with, any promotional activities or solicitation by
              anyone in any jurisdiction in which such promotional activities or
              solicitation are not authorised or to any person to whom it is
              unlawful to promote or solicit.
            </p>

            <p className="mb-4">
              j) Prices for any product(s) displayed on the platform may be
              inaccurate due to technical issues, typographical errors, or
              incorrect information provided by the seller. In such cases, the
              seller is responsible and reserves the right to cancel the user’s
              order(s). The offer listing is not a binding agreement between the
              user and businesses.
            </p>

            <p className="mb-4">
              k) OfferBeez accepts no responsibility for any breaches of
              applicable laws, including those governing the products and offers
              offered by sellers or third-party delivery service providers or by
              payment gateway service providers.
            </p>

            <p className="mb-4">
              l) You acknowledge that third-party offers are available on the
              platform, and we may partner with certain third parties to
              facilitate such offers. However, you agree that we make no
              representations or warranties regarding these third-party offers
              or products and will not be liable for any outcomes, including
              injury, impairment, or death, resulting from their use. You hereby
              waive any rights or claims you may have against us in relation to
              third-party offers.
            </p>

            {/* ---------- 12. Indemnification and Limitation of Liability ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              12. Indemnification and Limitation of Liability:
            </h2>

            <p className="mb-4">
              a) You agree to indemnify, defend and hold harmless OfferBeez,
              Partners, Sellers, service providers, its officers, directors,
              consultants, agents, representatives and employees, and its
              third-party partners (“Indemnitees”) from and against any and all
              losses, liabilities, claims, damages, demands, costs and expenses
              (including reasonable legal fees) asserted against or incurred by
              the Indemnitees that arise out of, result from, or may be payable
              by virtue of, any breach or non-performance of any representation,
              warranty, covenant or agreement made or obligation to be performed
              by You pursuant to these Terms and/or the Privacy Notice. Further,
              You agree to hold the Indemnitees harmless against any claims made
              by any third party due to, or arising out of, or in connection
              with, Your use of the Platform, any misrepresentation with respect
              to the data or information provided by You, Your violation of the
              Terms and/or the Privacy Notice, Your violation of applicable
              laws, or Your violation of any rights of third parties, including
              any intellectual property rights.
            </p>

            <p className="mb-4">
              b) In no event shall OfferBeez, its sellers, its service
              providers, its directors, officers, partners, consultants, agents,
              and employees, and its partners be liable to you or any third
              party for any special, incidental, indirect, consequential, or
              punitive damages whatsoever arising out of or in connection with
              your use of or access to the Platform or Content on the Platform.
            </p>

            <p className="mb-4">
              c) Notwithstanding any provisions herein, OfferBeez, Sellers, and
              service providers’ maximum total liability shall not exceed the
              amount paid by the User for the purchase of the Product and/or
              Offers under the specific order to which the liability relates.
            </p>

            <p className="mb-4">
              d) The limitations and exclusions in this section apply to the
              maximum extent permitted by applicable laws.
            </p>

            {/* ---------- 13. Violation of these Terms ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              13) Violation of these Terms:
            </h2>

            <p className="mb-4">
              You agree that any violation by you of these terms will likely
              cause irreparable harm to OfferBeez, for which monetary damages
              would be inadequate, and you consent to OfferBeez obtaining any
              injunctive or equitable relief that they deem necessary or
              appropriate in such circumstances. These remedies are in addition
              to any other remedies that OfferBeez may have at law or in equity.
            </p>

            {/* ---------- 14. Suspension and Termination ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              14) Suspension and Termination:
            </h2>

            <p className="mb-4">
              a) The Terms will continue to apply until terminated by either you
              or OfferBeez as set forth below. If You object to the Terms or are
              dissatisfied with the Platform, You may:
            </p>

            <ul className="list-disc list-inside mb-4">
              <li>Close Your Account on the Platform</li>
              <li>Stop accessing the Platform.</li>
            </ul>

            <p className="mb-4">
              b) OfferBeez may disable Your access or block Your future access
              to the Platform or suspend or terminate Your Account if it
              believes, in its sole and absolute discretion, that You have
              violated any term of these Terms or the Privacy Notice or in any
              way otherwise acted unethically. Notwithstanding anything
              contained herein, all terms which by their nature are intended to
              survive such termination will survive indefinitely unless and
              until OfferBeez chooses to terminate them.
            </p>

            <p className="mb-4">
              c) Any such termination shall not cancel your obligation to pay
              for a product or a service purchased on the Platform, or any other
              obligation which has accrued or is unfulfilled and relates to the
              period prior to termination.
            </p>

            <p className="mb-4">
              d) You shall be liable to pay any fees or charges, if applicable,
              in respect of the offers until the date of termination by either
              party whatsoever.
            </p>

            {/* ---------- 15. Governing Law and Jurisdiction ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              15) Governing Law and Jurisdiction:
            </h2>

            <p className="mb-4">
              These Terms shall be governed by and construed in accordance with
              the laws of India without reference to conflict of laws
              principles, and disputes arising in relation hereto shall be
              subject to the exclusive jurisdiction of courts at Bengaluru,
              Karnataka, India.
            </p>

            {/* ---------- 16. Grievance Redressal Mechanism ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              16) Grievance Redressal Mechanism:
            </h2>

            <p className="mb-4">
              a) For any order-related issue, you may first reach out to us via
              chat support on the app for real-time basis resolution.
            </p>

            <p className="mb-4">
              b) You may also write to us at{" "}
              <span className="font-medium">support@OfferBeez.in</span>, and we
              will strive to resolve your order-related issues within the
              timelines prescribed under applicable laws.
            </p>

            <p className="mb-4">
              c) If you still have any grievances or complaints or concerns with
              respect to the Platformer order or are not satisfied with the
              resolution, the content, or the offers, you can contact the
              designated Grievance cum Nodal Officer of OfferBeez as per the
              below details:
            </p>

            <h4 className=" font-bold">Mr Arun</h4>

            <h4 className=" font-bold">Designation: Associate Director</h4>

            <h4 className=" font-bold">
              Venturebiz Promotions Private Limited
            </h4>

            <h4 className=" font-bold">
              Address: #2085/16, 2nd Floor, Spoorthi,
              <br />
              Puttenahalli Main Road,
              <br />
              JP Nagar 7th Phase,
              <br />
              Bangalore-560078.
            </h4>

            <h4 className=" font-bold">Phone: 900852236</h4>

            <h4 className="mb-4 font-bold">Email: grievances@offerbeez.in</h4>

            <h4 className=" font-bold">Time: Mon – Sat (9:00 – 18:00) are</h4>

            <p className="mb-4">
              a) The aforementioned details of the Grievance cum Nodal Officer
              are provided in compliance with the Information Technology Act,
              2000, and rules made thereunder.
            </p>

            <p className="mb-4">
              b) Consumer Protection (E-Commerce) Rules 2020, as amended from
              time to time.
            </p>

            <p className="mb-4">
              c) The Grievance Officer of OfferBeez shall endeavour to
              acknowledge the user grievances, complaints, or concerns with
              respect to the platform, the content, or the offers, within 48
              hours of receipt of the same and shall endeavour to redress the
              same at the earliest and in no event later than 30 (thirty) days
              of receipt of such request. By lodging a complaint or grievance,
              you agree to provide complete support to the Grievance Officer and
              such reasonable information as may be sought by them from you.
            </p>

            {/* ---------- 17. Notice of Infringement and Take Down Policy ---------- */}
            <h2 className="font-bold mt-6 mb-4">
              17) Notice of Infringement and Take Down Policy
            </h2>

            <p className="mb-4">
              a) OfferBeez’s Take Down Policy enables intellectual property
              owners to quickly report and remove infringing listings from the
              platform.
            </p>

            <p className="mb-4">
              b) Intellectual property owners can report potentially infringing
              products or listings by submitting a Notice of Infringement
              containing all the details as mentioned below. OfferBeez cannot
              independently verify that sellers have the rights to sell or
              distribute their products or offers but is fully committed to
              protecting intellectual property rights.
            </p>

            <p className="mb-4">c) Steps to report a listing:</p>

            <p className="mb-4">
              If you have a sincere belief that a seller on our platform is
              infringing your intellectual property rights, please follow the
              below steps. We request you to provide the following information
              and email it to
              <span className="font-medium"> legal@OfferBeez.in</span>. The
              email should include:
            </p>

            <ol className="list-decimal list-inside mb-4 space-y-2">
              <li>
                Identification or description of the copyrighted work/trademark
                that has been infringed along with regplatform./application
                details and images.
              </li>
              <li>Your contact information.</li>
              <li>
                An undertaking from you that you have a good faith belief that
                the use of the material complained of is not authorised by the
                trademark or copyright or intellectual property owner, its
                agent, or the law.
              </li>
              <li>
                The information in the notice is accurate, and you are the
                trademark or copyright or intellectual property owner or
                authorised to act on the trademark or copyright or intellectual
                property owner's behalf.
              </li>
              <li>
                Such other information that You think is important for
                supporting Your claim.
              </li>
            </ol>

            {/* ---------- 18. OfferBeez’s Actions ---------- */}
            <h2 className="font-bold mt-6 mb-4">18) OfferBeez’s Actions:</h2>

            <p className="mb-4">
              a) Upon receiving a duly completed notice with the necessary
              documentation as described above, and after confirming the
              authenticity of the claim, OfferBeez may take steps to remove or
              disable access to the alleged infringing content provided by third
              parties.
            </p>

            <p className="mb-4">
              b) OfferBeez may also inform the respective seller who submitted
              the content in question, providing them with a copy of the
              infringement notice.
            </p>

            <p className="mb-4">
              c) We reserve the right to undertake any further actions as
              permitted by the applicable laws in effect at the time of
              notification.
            </p>

            {/* ---------- 19. Communications ---------- */}
            <h2 className="font-bold mt-6 mb-4">19) Communications:</h2>

            <p className="mb-4">
              a) You hereby expressly agree to receive communications by way of
              SMS, telephone or VoIP calls, messaging apps like WhatsApp on the
              registered mobile phone number and/or electronic communications
              like e-mails from OfferBeez and other third parties duly
              authorised by OfferBeez.
            </p>

            <p className="mb-4">
              b) You hereby expressly consent to the monitoring and recording,
              by OfferBeez and/or any third party, of any and all communications
              between you and OfferBeez or its agents, employees, consultants,
              contractors, or representatives of OfferBeez or of their
              authorised partners, and such monitoring or recording waives any
              further notice or consent requirement under the applicable laws.
            </p>

            <p className="mb-4">
              c) You can unsubscribe or opt out from receiving promotional
              communications from OfferBeez. In which case, OfferBeez will only
              send communications solely required for the purposes of availing
              the offers by you.
            </p>

            {/* ---------- 20. General Provisions ---------- */}
            <h2 className="font-bold mt-6 mb-4">20) General Provisions:</h2>

            <h3 className="font-semibold ">Notice:</h3>
            <p className="mb-4">
              a) All notices from OfferBeez will be served by email to your
              registered email address, by messaging app on the registered
              mobile phone number or by general notification on the platform.
            </p>

            <h3 className="font-semibold ">Assignment:</h3>
            <p className="mb-4">
              b) You cannot assign or otherwise transfer any rights granted
              hereunder to any third party. OfferBeez’s rights and obligations
              under the Terms are freely transferable by OfferBeez to its
              successor or to its affiliates or any third party without the
              requirement of seeking your consent.
            </p>

            <h3 className="font-semibold">Severability:</h3>
            <p className="mb-4">
              c) If, for any reason any provision of the Terms, or any portion
              thereof, to be unenforceable, that provision shall be enforced to
              the maximum extent permissible so as to give effect to the intent
              of the parties as reflected by that provision, and the remainder
              of the Terms shall continue in full force and effect.
            </p>

            <h3 className="font-semibold">Force Majeure:</h3>
            <p className="mb-4">
              d) OfferBeez, its Sellers, its service providers shall not be
              liable to You for its failure to perform or for delay in providing
              You access to Your Account or to the Platform or any Offers
              thereof, to the extent such failure or delay results from causes
              beyond its reasonable control, including, without limitation, acts
              of God, fires, explosions, wars or other hostilities,
              insurrections, revolutions, strikes, labour unrest, earthquakes,
              floods, riots, excessive rains, pandemic, epidemics or regulatory
              or quarantine restrictions, unforeseeable governmental
              restrictions or controls or a failure by a third party hosting
              provider or internet service provider or on account of any change
              or defect in the software and/or hardware of Your computer system.
            </p>

            {/* ---------- 21. Advertisements ---------- */}
            <h2 className="font-bold mt-6 mb-4">21) Advertisements:</h2>

            <p className="mb-4">
              a) As part of the offers provided by us, we may facilitate and
              allow third-party advertisers (“Third-Party Advertisers”) to place
              advertisements on the Platform. You understand that any content
              put out by third-party advertisers is endorsed by OfferBeez, and
              we disclaim to the fullest extent permitted by law any liability
              for the content published by the third-party advertisers. It is
              solely the responsibility of the third-party advertisers
              submitting material to the platform to ensure compliance with all
              relevant laws. Any interactions or transactions you undertake with
              third-party advertisers found on the platform, including payments,
              delivery, and terms or representations related to their goods or
              offers, are strictly between you and the third-party advertiser.
              OfferBeez bears no liability for errors, omissions, or
              inaccuracies in advertising content or for any losses or damages
              arising from your dealings with these advertisers or their
              presence on the platform.
            </p>

            <p className="mb-4">
              b) To the extent You are a Third Party Advertiser, You understand
              that in addition to these Terms, You will also be required to
              agree to OfferBeez’s policies and other contractual agreements
              that You will need to execute for placing Your advertisement.
            </p>

            <p className="mb-4">
              c) As a general principle, the content in the advertisements
              should not be misleading or in violation of applicable law or
              guidelines issued by the Advertising Standards Council of India or
              any other self-regulating body. You also acknowledge that We have
              the sole right at Our discretion to remove any Third Party
              Advertisement or require You to prove factual substantiation if We
              are of the view that it is in violation of applicable law or any
              self-regulating industry body guidelines or is otherwise
              misleading.
            </p>

            <p className="mb-4">
              d) If you are of the view that the content of a third-party
              advertiser is inappropriate or in violation of applicable law,
              please write to Us at the email address provided above.
            </p>

            <p className="mb-4">
              e) For any charitable campaign information shared with users or
              displayed on the platform, where donations may be made through
              third-party sites or accounts, OfferBeez may not be involved in
              fund collection or use. OfferBeez bears no responsibility for the
              accuracy or legality of campaign information, which is provided
              solely for reference. Users are encouraged to verify details
              independently before taking action.
            </p>

            {/* ---------- 22. Severability ---------- */}
            <h2 className="font-bold mt-6 mb-4">22) Severability:</h2>

            <p className="mb-4">
              a) If any part of these Terms is found to be invalid, void, or
              unenforceable, that portion will be treated as separable, and the
              remaining provisions will continue in full force and effect.
            </p>

            {/* ---------- 23. Amendments ---------- */}
            <h2 className="font-bold mt-6 mb-4">23) Amendments:</h2>

            <p className="mb-4">
              a) We may modify these Terms periodically, without prior notice,
              to include updates, revisions, additions, or new policies
              affecting your use of the offers. Such changes will be posted on
              the platform and take effect immediately upon posting. We
              encourage you to review these terms on the platform regularly for
              any updates. By continuing to use the Offers and/or the Platform,
              you agree to accept any revised Terms.
            </p>

            {/* ---------- 24. Transition ---------- */}
            <h2 className="font-bold mt-6 mb-4">24) Transition:</h2>

            <p className="mb-4">
              a) THE PLATFORM IS UNDERGOING A TRANSITION WHERE THE PLATFORM WILL
              BE OPERATED BY VENTUREBIZ PROMOTIONS PRIVATE LIMITED FROM THE DATE
              WHICH SHALL BE COMMUNICATED TO YOU. PURSUANT TO THE TRANSITION,
              THE EXISTING USER OF OFFERBEEZ OFFERS HEREBY CONSENTS TO THE
              FOLLOWING:
            </p>

            <p className="mb-4">
              b) FOR THE TRANSFER OF YOUR PAYMENT-RELATED INFORMATION AND
              INSTRUMENTS AS AVAILABLE WITH THE SERVICE PROVIDER OF OFFERBEEZ TO
              ENSURE A SEAMLESS EXPERIENCE FOR USERS POST TRANSITION.
            </p>

            {/* ---------- 25. Entire Agreement ---------- */}
            <h2 className="font-bold mt-6 mb-4">25) Entire Agreement:</h2>

            <p className="mb-4">
              a) This document, including the Privacy Notice and any policies
              that OfferBeez may introduce from time to time, represents the
              entire understanding between you and OfferBeez. It establishes the
              terms for your access to and use of the offers and platform,
              superseding any earlier arrangements related to such access or
              use.
            </p>

            <p className="mb-4 font-semibold">
              <a
                href="https://www.venturebiz.in"
                className="text-[#3345B0] hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                © 2025 Venturebiz Promotions Private Limited
              </a>{" "}
              All rights reserved.
            </p>
          </div>
        </div>
      </main>

        {/* (Optional) Local Footer for this page */}
      <footer className="w-full bg-[#3345B0] text-white py-6 mt-16">
        <div className="max-w-6xl mx-auto px-6 text-center text-sm">
          <p>© 2025 OfferBeez. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default ConsumerTOS;